name: skilloka_mobile
description: Skilloka - Platform Agregator Pelatihan Vokasi Hyperlocal
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Navigation
  go_router: ^14.2.0
  
  # Network
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3
  
  # Local Storage
  flutter_secure_storage: ^9.2.2
  hive_flutter: ^1.1.0
  
  # UI Components
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.1.0
  flutter_svg: ^2.0.10+1
  
  # Location
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  
  # Payment & QR
  qr_flutter: ^4.1.0
  mobile_scanner: ^4.0.1
  
  # Utils
  intl: ^0.19.0
  dartz: ^0.10.1
  get_it: ^7.6.9
  
  # Google Fonts
  google_fonts: ^6.2.1
  
  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
  
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
